packages:
  - "apps/*"
  - "packages/*"
catalog:
  # Monorepo
  turbo: ^2.5.5
  "@turbo/gen": ^2.5.5

  # TypeScript
  "@types/node": ^22.15.30
  "typescript": ^5.8.2
  "ts-node": ^10.9.2

  # Biome
  "@biomejs/biome": ^2.1.2

  # React
  "react": ^19.1.0
  "react-dom": ^19.1.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1

  # Next.js
  "@next/bundle-analyzer": ^15.4.1
  "@t3-oss/env-nextjs": ^0.13.8
  next: ^15.4.1
  next-themes: ^0.4.4

  # tailwind css
  "@tailwindcss/cli": ^4.1.5
  "@tailwindcss/postcss": ^4.1.5
  tailwindcss: ^4.1.5
  tailwindcss-animate: ^1.0.7
  tailwind-merge: ^2.6.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  lucide-react: ^0.469.0
  postcss: ^8.5.3
  autoprefixer: ^10.4.20

  # Type safe
  zod: ^4.0.5
  "@t3-oss/env-core": ^0.13.8
  "@t3-oss/env-next.js": ^0.13.8

  # dotenv
  "dotenv": ^16.4.7
  "dotenv-cli": ^8.0.0
