packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.1.2
  '@next/bundle-analyzer': ^15.4.1
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-next.js': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@tailwindcss/cli': ^4.1.5
  '@tailwindcss/postcss': ^4.1.5
  '@turbo/gen': ^2.5.5
  '@types/node': ^22.15.30
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.1
  autoprefixer: ^10.4.20
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^16.4.7
  dotenv-cli: ^8.0.0
  lucide-react: ^0.469.0
  next: ^15.4.1
  next-themes: ^0.4.4
  postcss: ^8.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.5
  tailwindcss-animate: ^1.0.7
  ts-node: ^10.9.2
  turbo: ^2.5.5
  typescript: ^5.8.2
  zod: ^4.0.5

onlyBuiltDependencies:
  - core-js-pure
