name: pull-request
on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pr-labeler:
    name: PR Labeler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        # workaround for sync-labels bug:
        # https://github.com/actions/labeler/issues/112#issuecomment-1000491676
        # sync-labels: ""
        configuration-path: ".github/labeler.yml"
  pr-assigner:
    name: Assign author to PR
    if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1
